version: '3'
services:
  kaleidos-frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kaleidos-frontend
    ports:
      - "8081:80"
    expose:
      - 8081
    environment:
      - EMBER_ENV=development
      - VIRTUAL_HOST=kaleidos-frontend.kanselarij-dev.s.redpencil.io
      - VIRTUAL_PORT=80
      - BACKEND=production-kaleidos_backend
      - LETSENCRYPT_HOST=kaleidos-frontend.kanselarij-dev.s.redpencil.io
    networks:
      - proxy
      - default
      - backend
    restart: always

networks:
  proxy:
    external:
      name: letsencrypt_default
  backend:
    external: true
