version: '3'
services:
  development-kaleidos-frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    ports:
      - "${APP_PORT}:80"
    expose:
      - 8081
    environment:
      - EMBER_ENV=development
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
    networks:
      - proxy
      - default
      - backend
    restart: always

networks:
  proxy:
    external:
      name: letsencrypt_default
  backend:
    external: true

